dist: trusty
language: ruby
sudo: true # need this for libgirepository1.0-dev
# sudo: false # taking advantage of container-based infrastructure
cache: bundler # cache bundled gems from build to build

branches:
  only:
  - master

addons:
  apt:
    packages:
      - libgirepository1.0-dev # for gobject-introspection

rvm: 2.4.0

install:
  - bundle install

script:
  - bundle exec rake

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd _output
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://avengerpenguin:$GITHUB_API_KEY@github.com/<me>/<myrepo>-gh-pages gh-pages
  fi
