language: ruby

before_install:
  - sudo apt-get install -V -y libgirepository1.0-dev
  - rvm install 2.4.0

install:
  - bundle install
  - pip install ghp-import

script: bundle exec rake deck page && ghp-import _output
