dist: trusty
language: ruby
sudo: true # need this for libgirepository1.0-dev
# sudo: false # taking advantage of container-based infrastructure
cache: bundler # cache bundled gems from build to build

addons:
  apt:
    packages:
      - libgirepository1.0-dev # for gobject-introspection

rvm: 2.4.0

install:
  - bundle install
  - sudo pip install ghp-import

script: bundle exec rake deck page && ghp-import _output
